apiVersion: template.openshift.io/v1
kind: Template
objects:

  # This networkPolicy is optional as is "included" in the second, but 
  # for the sake of clarity, I'm adding it to the configuration
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: deny-by-default
      namespace: ${APP_NAMESPACE}
    spec:
      podSelector: {}
      policyTypes:
        - Ingress

  # This is the main restricting policy, it denies traffic from outside the ns
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-same-namespace
      namespace: ${APP_NAMESPACE}
    spec:
      podSelector: {}
      ingress:
      - from:
        - podSelector: {}

  # To allow requests through the OCP Route
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      namespace: ${APP_NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              policy-group.network.openshift.io/ingress: ""
      podSelector: {}
      policyTypes:
      - Ingress

  # To allow access from Prometheus (Infra and user-workload)
  # More info here: https://access.redhat.com/solutions/6247871
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-monitoring
      namespace: ${APP_NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: monitoring
      podSelector: {}
      policyTypes:
      - Ingress

  # This is needed for namespaces that are running pods of Mutating and Validating Webhooks
  # In general, this is not needed for application namespaces, but it is not harmful, as 
  # only the kube-apiserver-operator running on its namespace will be able to use it.
  # It could happen that you install a namespaced operator that defines a webhook in your namespace
  # and in that case, you would need it.
  # More information here: https://access.redhat.com/solutions/6964520
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-kube-apiserver-operator
      namespace: ${APP_NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-kube-apiserver-operator
          podSelector:
            matchLabels:
              app: kube-apiserver-operator
      policyTypes:
      - Ingress


  # Add NetworkPolicy to allow Openshift Logging pods to get Logs from the app
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-logging
      namespace: ${APP_NAMESPACE}
    spec:
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: openshift-logging
      podSelector: {}
      policyTypes:
      - Ingress

parameters:
  - name: APP_NAMESPACE
    description: "The project where the application will be deployed."
    required: false
    value: quarkus-observability
