---
apiVersion: template.openshift.io/v1
kind: Template
objects:

  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      name: ${SECRET_NAMESPACE}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
      namespace: ${SECRET_NAMESPACE}
    stringData:
      access_key_id: ${AWS_ACCESS_KEY_ID}
      access_key_secret: ${AWS_SECRET_ACCESS_KEY}
      bucket: ${AWS_S3_BUCKET} # Only used in Tempo
      name: ${AWS_S3_BUCKET} # Only used in Tempo
      endpoint: https://s3.${AWS_DEFAULT_REGION}.amazonaws.com

parameters:
  - name: SECRET_NAMESPACE
    description: "The project where the secret is created."
    required: true
  - name: SECRET_NAME
    description: "Name of the Bucket secret."
    required: true
  - name: AWS_ACCESS_KEY_ID
    description: "AWS access_key_id."
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: "AWS access_key_secret."
    required: true
  - name: AWS_DEFAULT_REGION
    description: "AWS region."
    required: true
  - name: AWS_S3_BUCKET
    description: "S3 Bucket name (You can modify it in the script)."
    required: true
