---
apiVersion: template.openshift.io/v1
kind: Template
objects:

  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        openshift.io/cluster-monitoring: "true"
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
      name: ${SECRET_NAMESPACE}

  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${SECRET_NAME}
      namespace: ${SECRET_NAMESPACE}
    type: Opaque
    stringData:
      password: ${AUTH_PASSWORD}

parameters:
  - name: SECRET_NAMESPACE
    description: "The project where the secret is created."
    required: false
    value: quarkus-observability
  - name: SECRET_NAME
    description: "Name of the Bucket secret."
    required: false
    value: alert-routing-to-mail
  - name: AUTH_PASSWORD
    description: "The APP password in Gmail."
    required: true  
