apiVersion: template.openshift.io/v1
kind: Template
objects:

  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${AWS_SECRET_NAME}
      namespace: ${LOGGING_NAMESPACE}
    stringData:
      aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
      aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"

  - apiVersion: logging.openshift.io/v1
    kind: ClusterLogForwarder
    metadata:
      name: instance 
      namespace: ${LOGGING_NAMESPACE}
    spec:
      inputs: 
        - name: quarkus-observability-logs
          application:
            namespaces:
              - quarkus-observability
      pipelines:
        - name: quarkus-observability
          inputRefs: 
            # - infrastructure
            # - audit
            # - application
            - quarkus-observability-logs
          outputRefs:
            - cw-output 
          parse: json 
          labels:
            test: "alvaro" 
      outputs:
        - name: cw-output
          type: cloudwatch 
          cloudwatch:
            groupBy: logType 
            groupPrefix: ${CLOUDWATCH_GROUP_PREFIX}
            region: ${AWS_DEFAULT_REGION}
          secret:
              name: ${AWS_SECRET_NAME} 

parameters:
  - name: LOGGING_NAMESPACE
    description: "The project where the logging stack is deployed."
    required: false
    value: openshift-logging
  - name: AWS_SECRET_NAME
    description: "The name of the secret with the credentials."
    required: false
    value: aws-cloudwatch-secret
  - name: AWS_ACCESS_KEY_ID
    description: "AWS access_key_id."
    required: true
  - name: AWS_SECRET_ACCESS_KEY
    description: "AWS access_key_secret."
    required: true
  - name: AWS_DEFAULT_REGION
    description: "AWS region."
    required: true
  - name: CLOUDWATCH_GROUP_PREFIX
    description: "Cloudwatch Group Prefix."
    required: false
    value: "ocp-cluster"
