app:
  greeting:
    message: "Hello from RESTEasy Reactive"
quarkus:
  log:
    console:
      json:
        ~: true
        # pretty-print: true
  micrometer:
    export:
      json: 
        enabled: true
        path: metrics-json
      prometheus: 
        path: metrics
  otel:
    enabled: true
    exporter:
      otlp:
        endpoint: "http://jaeger-collector.tracing-system.svc.cluster.local:4317/"
  swagger-ui:
    always-include: true
  smallrye-openapi:
    path: /q/swagger
    info-title: Quarkus Observability App
    info-version: 1.0.2
    info-description: Just a simple app to test Metrics, Logging, Tracing, etc.
    info-contact-name: Alvaro Lopez Medina
    info-license-name: GNU General Public License v3.0
    info-license-url: https://github.com/alvarolop/quarkus-observability-app/blob/main/LICENSE
