---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: telemetrygen
  name: telemetrygen
  namespace: tracing-app-telemetrygen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telemetrygen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telemetrygen
    spec:
      # in total 5 spans per second are generated, with 2/5 (40%) containing an error
      containers:
      # this generates 3 spans per second
      - name: telemetrygen1
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - traces
          - --otlp-endpoint=user-collector.openshift-tracing:4317
          - --otlp-insecure
          - --duration=1h
          - --service=good_service
          - --rate=3 # spans per second
          - --child-spans=2
      # this generates 2 spans per second with an error status
      - name: telemetrygen2
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.105.0
        args:
          - traces
          - --otlp-endpoint=user-collector.openshift-tracing:4317
          - --otlp-insecure
          - --duration=1h
          - --service=faulty_service
          - --rate=2 # spans per second
          - --child-spans=1
          - --status-code=Error