---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-opentelemetry-gen-hotrod.yaml
  - ns-opentelemetry-gen-k6.yaml
  - ns-opentelemetry-gen-telemetrygen.yaml
  - deployment-hotrod.yaml
  - deployment-k6-tracing.yaml
  - deployment-telemetrygen.yaml
  - svc-hotrod.yaml
  - route-hotrod.yaml

  - opentelemetry-gen-simple-demo
