---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: opentelemetry-gen-hotrod
spec:
  selector:
    app.kubernetes.io/name: hotrod
  ports:
  - name: frontend
    port: 8080
    targetPort: frontend
