---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-observability

resources:

  # Secret to provide email credentials
  # Created during prereqs due to confidentiality
  # - secret-alert-routing-to-mail.yaml

  # Rule to trigger alerts
  - prometheusrule-quarkus-app.yaml

  # Alert notification configuration
  - alertmanagerconfig-alert-routing-to-mail.yaml
  - alertmanagerconfig-alert-routing-to-mail-label.yaml
