apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    enableUserWorkload: true
    alertmanagerMain:
      enabled: true
      enableUserAlertmanagerConfig: false
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusK8s:
      # Specify the maximum body size for scraped metrics targets.
      enforcedBodySizeLimit: 40MB
      retention: 24h
      retentionSize: 10GB
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    # prometheusOperatorAdmissionWebhook:
    openshiftStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    metricsServer:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    telemeterClient:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    thanosQuerier:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    monitoringPlugin:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    # nodeExporter:
    #   collectors: 
