---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    alertmanager:
      enabled: true
      enableAlertmanagerConfig: true
    prometheus:
      # Maximum number of labels per scrape
      enforcedLabelLimit: 500 
      # Maximum length in characters of a label name
      enforcedLabelNameLengthLimit: 50 
      # Maximum length in characters of a label value
      enforcedLabelValueLengthLimit: 600 
      # Attach custom labels to every user metric
      externalLabels:
        region: alvaro
        environment: lab
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 4
          memory: 8Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    thanosRuler:
      nodeSelector:
        node-role.kubernetes.io/infra: ""