---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque 
stringData: 
  alertmanager.yaml: |-     
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
      - equal:
          - namespace
          - alertname
        source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
      - equal:
          - namespace
        source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
    receivers:
      - name: Default
      - name: Watchdog
      - name: Critical
      - name: 'null'
      # - name: email-notification
      #   email_configs:
      #     - to: alvarolop.medina@gmail.com
      #       from: ${AUTH_USERNAME}
      #       smarthost: smtp.gmail.com:587
      #       auth_username: ${AUTH_USERNAME}
      #       auth_password: ${AUTH_PASSWORD}
    route:
      group_by:
        - namespace
        - alertname
      group_interval: 5m
      group_wait: 30s
      receiver: Default
      repeat_interval: 12h
      routes:             
        - matchers:
            - alertname = Watchdog
          receiver: Watchdog
          # continue: true
        # - matchers:
        #     - alertname = Watchdog
        #   receiver: email-notification
        - matchers:
            - alertname = InfoInhibitor
          receiver: 'null'
        - matchers:
            - severity = critical
          receiver: Critical
