---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

configMapGenerator:

  - name: tempo-operational-dashboard
    files:
      - dashboards-mixin-compiled/tempo-operational.json
    options:
      disableNameSuffixHash: true
  - name: tempo-reads-dashboard
    files:
      - dashboards-mixin-compiled/tempo-reads.json
    options:
      disableNameSuffixHash: true
  - name: tempo-resources-dashboard
    files:
      - dashboards-mixin-compiled/tempo-resources.json
    options:
      disableNameSuffixHash: true
  - name: tempo-rollout-progress-dashboard
    files:
      - dashboards-mixin-compiled/tempo-rollout-progress.json
    options:
      disableNameSuffixHash: true
  - name: tempo-tenants-dashboard
    files:
      - dashboards-mixin-compiled/tempo-tenants.json
    options:
      disableNameSuffixHash: true
  - name: tempo-writes-dashboard
    files:
      - dashboards-mixin-compiled/tempo-writes.json
    options:
      disableNameSuffixHash: true

resources:

  - dashboard-tempo-operational.yaml
  - dashboard-tempo-reads.yaml
  - dashboard-tempo-resources.yaml
  - dashboard-tempo-rollout-progress.yaml
  - dashboard-tempo-tenants.yaml
  - dashboard-tempo-writes.yaml

  - datasource-tempo.yaml
