apiVersion: template.openshift.io/v1
kind: Template
objects:

  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: ${APP_NAMESPACE}
      annotations:
        openshift.io/description: "Project to deploy the observability app"
        openshift.io/display-name: "Observability Test Environment"

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/name: ${APP_NAME}
        app.openshift.io/runtime: quarkus
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${APP_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deployment: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: quay.io/alopezme/quarkus-observability-app:latest-micro
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /q/health/live
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /q/health/ready
                  port: 8080
                  scheme: HTTP
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              resources:
                limits:
                  cpu: 300m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 50Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - ALL
              volumeMounts:
                - name: app-config
                  mountPath: "${MOUNT_PATH}"
          volumes:
            - name: app-config
              configMap:
                name: ${APP_NAME}-config
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      type: ClusterIP
      selector:
        app: ${APP_NAME}
        deployment: ${APP_NAME}

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ${APP_NAME}
      namespace: ${APP_NAMESPACE}
      labels:
        app: ${APP_NAME}
    spec:
      to:
        kind: Service
        name: ${APP_NAME}
      port:
        targetPort: 8080-tcp
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None

parameters:
  - name: APP_NAMESPACE
    description: "The project where the application will be deployed."
    required: false
    value: quarkus-observability
  - name: APP_NAME
    description: "The name of the application."
    required: false
    value: app
  - name: MOUNT_PATH
    description: "The path where the configuration file of the application is mounted."
    value: "/work/config"
    required: true
