---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-prometheus-token-secret
rules:
- resources:
  - serviceaccounts
  verbs:
  - get
  - list
- resources:
  - secrets
  verbs:
  - get
  - list
  - create
