---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-prometheus-token-secret
spec:
  template:
    spec:
      containers:
      - name: create-prometheus-token-secret
        image: registry.redhat.io/openshift4/ose-cli-rhel9:latest
        command:
        - "/bin/bash"
        - "-c"
        - |
          GRAFANA_NAMESPACE="grafana"
          SA_NAME="grafana-sa"

          # Retrieve the token from the service account
          TOKEN_SECRET=$(oc describe sa $SA_NAME -n $GRAFANA_NAMESPACE | awk '/Tokens/{ print $2 }')
          BEARER_TOKEN=$(oc get secret $TOKEN_SECRET -n $GRAFANA_NAMESPACE --template='{{ .data.token | base64decode }}')

          # Create the Secret with the retrieved token
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: credentials
            namespace: $GRAFANA_NAMESPACE
          stringData:
            PROMETHEUS_TOKEN: $BEARER_TOKEN
          type: Opaque
          EOF
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: job-create-prometheus-token-secret
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 300  # Job will be deleted 5 mins after completion
