---
apiVersion: batch/v1
kind: Job
metadata:
  name: alvaro
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  activeDeadlineSeconds: 240
  template:
    spec:
      containers:
      - name: create-prometheus-token-secret
        image: registry.redhat.io/openshift4/ose-cli-rhel9:latest
        command:
        - "/bin/bash"
        - "-c"
        - |
        
          GRAFANA_NAMESPACE="grafana"
          SA_NAME="grafana-sa"

          echo -n "Waiting for ServiceAccount ready..."
          while ! oc get sa grafana-sa -n $GRAFANA_NAMESPACE &> /dev/null; do   echo -n "." && sleep 1; done; echo -n -e " [OK]\n"
          sleep 10

          TOKEN_SECRET=$(oc describe sa $SA_NAME -n $GRAFANA_NAMESPACE | awk '/Tokens/{ print $2 }')

          echo -n "Waiting for the Token Secret ($TOKEN_SECRET) ready..."
          while ! oc get secret $TOKEN_SECRET -n $GRAFANA_NAMESPACE &> /dev/null; do   echo -n "." && sleep 1; done; echo -n -e " [OK]\n"
          sleep 10

          BEARER_TOKEN=$(oc get secret $TOKEN_SECRET -n $GRAFANA_NAMESPACE --template='{{ .data.token | base64decode }}')

          # Create the Secret with the retrieved token
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: credentials
            namespace: $GRAFANA_NAMESPACE
          stringData:
            PROMETHEUS_TOKEN: $BEARER_TOKEN
          type: Opaque
          EOF
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: job-create-prometheus-token-secret
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 300  # Job will be deleted 5 mins after completion
