---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-prometheus-token-secret
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
