{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: Delete={{ not .Values.operator.keepOnUninstall }}
  name: openshift-netobserv-operator
{{- end }}
