{{- if .Values.operator.enabled }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-netobserv-operator
  namespace: openshift-netobserv-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Delete={{ .Values.operator.keepOnUninstall | default true | not }}
spec:
  upgradeStrategy: Default
{{- end }}
