---
kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1alpha1
metadata:
  name: otel
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true 
  config: |
    connectors:
      spanmetrics: 
        metrics_flush_interval: 15s

    receivers:
      otlp: 
        protocols:
          grpc:
          http:

    exporters:
      otlp:
        endpoint: tempo-tempo-distributor.openshift-tempo.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus: 
        endpoint: 0.0.0.0:8889
        add_metric_suffixes: false
        resource_to_telemetry_conversion:
          enabled: true # by default resource attributes are dropped

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp, spanmetrics]
        metrics:
          receivers: [spanmetrics]
          exporters: [prometheus]