---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-observability

configMapGenerator:
  - name: app-config
    files:
      - application-ocp.yml
    options:
      disableNameSuffixHash: true

resources:
  - ns-quarkus-observability.yaml
  - deployment-app.yaml
  - svc-app.yaml
  - route-app.yaml

  - servicemonitor-app-quarkus-observability.yaml
