---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-quarkus-observability
  labels:
    app: app
spec:
  endpoints:
    - interval: 10s
      port: 8080-tcp
      path: /q/metrics
      scheme: http
  selector:
    matchLabels:
      app: app
  targetLabels:
    - app
