---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - operator

  # Logs Storage
  - lokistack-loki.yaml

  # Obtained from https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html-single/network_observability/index#nw-status-configuration-network-observability-operator_nw-network-observability-operator
  - flowcollector-cluster.yaml

