---
apiVersion: batch/v1
kind: Job
metadata:
  name: resolve-consolelink-url
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 10
  activeDeadlineSeconds: 240
  template:
    spec:
      containers:
      - name: resolve-consolelink-url
        image: registry.redhat.io/openshift4/ose-cli-rhel9:latest
        command:
        - "/bin/bash"
        - "-c"
        - |
          TEMPO_URL=$(oc get route tempo-tempo-query-frontend -n openshift-tempo -o jsonpath='{.spec.host}')
          echo "The Jaeger UI (Tempo) URL is $TEMPO_URL"
          if [[ -n "$TEMPO_URL" ]]; then
              oc patch consolelink openshift-tempo-tempo --type=merge -p '{"spec":{"href":"https://'"$TEMPO_URL"'"}}'
          else
              echo "Route not found, cannot create ConsoleLink"
              exit 1
          fi
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: job-resolve-consolelink-url
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 300  # Job will be deleted 5 mins after completion
