---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-tempo

resources:
  - consolelink-openshift-tempo-tempo.yaml
  - cr-resolve-consolelink-url.yaml
  - crb-job-resolve-consolelink-url.yaml
  - sa-job-resolve-consolelink-url.yaml
  - job-resolve-consolelink-url.yaml
