{
 "title": "Quarkus Observability Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(app_hello_counter_total,namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(app_hello_counter_total,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Replica count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Up in $namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replicas Up - History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "Count {{pod}}"
    }
   ]
  },
  { "title": "Quarkus Observability Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(app_hello_counter_total[1m])",
     "legendFormat": "Rate {{pod}}:/hello "
    },
    {
     "expr": "rate(app_hello_delayed_counter_total[1m])",
     "legendFormat": "Rate {{pod}}:/hello-delayed"
    }
   ]
  },
  { "title": "OCP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{resource=\"cpu\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Limit {{namespace}}"
    },
    {
     "expr": "kube_pod_resource_request{resource=\"cpu\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=\"$pod\",container=''}) by (pod)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{resource=\"memory\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "kube_pod_resource_request{resource=\"memory\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Request {{pod}}"
    }
   ]
  }
 ]
}