---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resolve-consolelink-url
  namespace: grafana
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
- apiGroups:
  - console.openshift.io
  resources:
  - consolelinks
  verbs:
  - get
  - list
  - patch
