---
apiVersion: batch/v1
kind: Job
metadata:
  name: resolve-consolelink-url
  namespace: grafana
spec:
  template:
    spec:
      containers:
      - name: consolelink-resolver
        image: registry.redhat.io/openshift4/ose-cli-rhel9:latest
        command:
        - "/bin/bash"
        - "-c"
        - |
          GRAFANA_URL=$(oc get route grafana-route -n grafana -o jsonpath='{.spec.host}')
          echo "Thhe Grafana URL is $GRAFANA_URL"
          if [[ -n "$GRAFANA_URL" ]]; then
              oc patch consolelink grafana-grafana --type=merge -p '{"spec":{"href":"https://'"$GRAFANA_URL"'"}}'
          else
              echo "Route not found, cannot create ConsoleLink"
              exit 1
          fi
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 300  # Job will be deleted 5 mins after completion
