---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operator
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  targetNamespaces:
    - grafana
