---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry-simple-demo

resources:
  - ns-opentelemetry-simple-demo.yaml
  
  - deployment-demo-client.yaml
  
  - deployment-demo-server.yaml
  - service-demo-server.yaml


## Build client image
# podman build opentelemetry-collector-contrib/examples/demo/client/ -t quay.io/alopezme/opentelemetry-simple-demo-client
# podman push quay.io/alopezme/opentelemetry-simple-demo-client

## Build server image
# podman build opentelemetry-collector-contrib/examples/demo/server/ -t quay.io/alopezme/opentelemetry-simple-demo-server
# podman push quay.io/alopezme/opentelemetry-simple-demo-server
