apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: grafana-consolelink
objects:

  - apiVersion: console.openshift.io/v1
    kind: ConsoleLink
    metadata:
      name: ${GRAFANA_NAMESPACE}-${GRAFANA_INSTANCE}
    spec:
      href: ${GRAFANA_ROUTE}
      location: ApplicationMenu
      text: Grafana
      applicationMenu:
        section: Observability
        imageURL: https://img.icons8.com/fluency/256/grafana.png

parameters:
- name: GRAFANA_ROUTE
  description: "The project where the cluster will be installed."
  required: true
- name: GRAFANA_NAMESPACE
  description: "The project where the cluster will be installed."
  required: false
  value: "grafana"
- name: GRAFANA_INSTANCE
  description: "The name of the Grafana cluster."
  required: false
  value: "grafana"
