---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: grafana-grafana
spec:
  href: "https://PLACEHOLDER-URL"
  location: ApplicationMenu
  text: Grafana
  applicationMenu:
    section: Observability
    imageURL: https://img.icons8.com/fluency/256/grafana.png
