---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-resolve-consolelink-url-graf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resolve-consolelink-url-graf
subjects:
- kind: ServiceAccount
  name: job-resolve-consolelink-url
  namespace: grafana
