---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  annotations:
    kubernetes.io/service-account.name: grafana-sa
    argocd.argoproj.io/sync-wave: "5"
type: kubernetes.io/service-account-token
