{
 "title": "App Observability Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(app_hello_counter_total,namespace)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(app_hello_counter_total,app)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(app_hello_counter_total{app=~\"$app\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replica count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Up in $namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=~\"$namespace\",app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Replicas Up - History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\",app=~\"$app\"}) by (pod)",
     "legendFormat": "Count {{pod}}"
    }
   ]
  },
  {
   "title": "Quarkus Observability Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(app_hello_counter_total{namespace=~\"$namespace\",app=~\"$app\"}[1m])",
     "legendFormat": "Rate {{pod}}:/hello "
    },
    {
     "expr": "increase(app_hello_delayed_counter_total{namespace=~\"$namespace\",app=~\"$app\"}[1m])",
     "legendFormat": "Rate {{pod}}:/hello-delayed"
    }
   ]
  },
  {
   "title": "OCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Used {{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Limit {{namespace}}"
    },
    {
     "expr": "kube_pod_resource_request{resource=\"cpu\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod\",container=''}) by (pod)",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "kube_pod_resource_limit{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Limit {{pod}}"
    },
    {
     "expr": "kube_pod_resource_request{resource=\"memory\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Request {{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"container_network_receive_bytes_total\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Rx {{pod}}"
    },
    {
     "expr": "- rate({__name__=~\"container_network_transmit_bytes_total\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Tx {{pod}}"
    }
   ]
  }
 ]
}