---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write-prod
rules:
  - apiGroups:
      - tempo.grafana.com
    resources: 
      - prod
    resourceNames:
      - traces
    verbs:
      - create
