---
# allow user-collector to read namespaces, pods and replicasets (required for k8sattributes processor)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-tracing-otel-collector
roleRef:
  kind: ClusterRole
  name: openshift-tracing-otel-collector
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: otel
