---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: openshift-otel
