---
kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true 
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    # Data sources: metrics
      prometheus:
        config:
          scrape_configs:
            - job_name: otel-collector
              scrape_interval: 5s
              static_configs:
                - targets: [localhost:8888]
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "tempo-tempo-distributor.openshift-tempo.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        add_metric_suffixes: false
        endpoint: 0.0.0.0:8889
        resource_to_telemetry_conversion:
          enabled: true # by default resource attributes are dropped
    connectors:
      spanmetrics: 
        metrics_flush_interval: 15s

    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
          processors: []
          receivers: []
            # - spanmetrics
        traces:
          exporters:
            - otlp
            # - spanmetrics
            - debug
          processors: []
          receivers:
            - otlp
