---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-network-policies
  name: ocp-network-policies
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: quarkus-observability
  project: default
  source:
    path: gitops/ocp-network-policies
    repoURL: https://github.com/alvarolop/quarkus-observability-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []
