---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: ocp-logging
  name: ocp-logging
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/ocp-logging
    repoURL: https://github.com/alvarolop/quarkus-observability-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
