---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: app-quarkus-observability
  name: app-quarkus-observability
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/app-quarkus-observability
    repoURL: https://github.com/alvarolop/quarkus-observability-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
