---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - application-grafana.yaml
  - application-ocp-alerting.yaml
  - application-ocp-coo.yaml
  - application-ocp-dist-tracing.yaml
  - application-ocp-logging.yaml
  - application-ocp-monitoring.yaml
  # - application-ocp-network-policies.yaml
  - application-quarkus-observability.yaml
 