---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-observability

resources:

- netpol-deny-by-default.yaml
- netpol-allow-same-namespace.yaml
- netpol-allow-from-openshift-ingress.yaml
- netpol-allow-from-openshift-monitoring.yaml
- netpol-allow-from-kube-apiserver-operator.yaml
