apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    alertmanagerMain:
      enabled: true
      enableUserAlertmanagerConfig: false
    prometheusK8s:
      # Specify the maximum body size for scraped metrics targets.
      enforcedBodySizeLimit: 40MB
      retention: 24h
      retentionSize: 10GB
    k8sPrometheusAdapter:
      # Deploy a dedicated service monitor that exposes the kubelet /metrics/resource endpoint.
      dedicatedServiceMonitors:
        enabled: true