{{- if .Values.kafkaExporter.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sasl-username
  namespace: netobserv
data:
  sasl-username.conf: |
    {{ .Values.kafkaExporter.username }}
{{- end }}