{{- if and .Values.kafkaExporter.enabled (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "kafkatopics.kafka.strimzi.io" "") }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: monitor-flows
  namespace: kafka
  labels:
    strimzi.io/cluster: cluster
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  config:
    retention.ms: 604800000
  partitions: 3
  replicas: 2
  topicName: {{ .Values.kafkaExporter.topic }}
{{- end }}
