{{- if .Values.flowCollector.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    netobserv-managed: "false"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: netobserv
{{- end }}