{{- if .Values.kafkaExporter.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: kafka-sasl-username
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "5"
stringData:
  username: {{ .Values.kafkaExporter.username }}
{{- end }}