{{- if .Values.kafkaExporter.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: kafka-sasl-username
  namespace: kafka
stringData:
  username: {{ .Values.kafkaExporter.username }}
{{- end }}