---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-tempo

resources:
  - ns-openshift-tempo.yaml
  - tempostack-tempo.yaml

  # Allow everybody to get traces
  - cr-tempostack-traces-reader-dev.yaml
  - cr-tempostack-traces-reader-prod.yaml
  - crb-tempostack-traces-reader-dev.yaml
  - crb-tempostack-traces-reader-prod.yaml
