---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # inputs: 
  #   - name: quarkus-observability-logs
  #     application:
  #       namespaces:
  #         - quarkus-observability
  # outputs: 
  #   - name: rsyslog-bastion
  #     type: syslog
  #     syslog:
  #       facility: local0
  #       rfc: RFC5424
  #       severity: informational
  #     url: 'tcp://X.X.X.X:514'   # Bastion
  pipelines:
    # - name: audit-logs
    #   inputRefs:
    #     - audit
    #   outputRefs:
    #     - rsyslog-bastion
    - name: default
      inputRefs:
        - application
        - infrastructure
        - audit
      outputRefs:
        - default


    spec:
      inputs: 
        - name: quarkus-observability-logs
          application:
            namespaces:
              - quarkus-observability
      pipelines:
        # - name: quarkus-observability
        #   inputRefs: 
        #     # - infrastructure
        #     # - audit
        #     # - application
        #     - quarkus-observability-logs
        #   outputRefs:
        #     - cw-output 
        #   parse: json 
        #   labels:
        #     test: "alvaro" 
        - name: enable-audit-logs
          inputRefs: 
            - audit
          outputRefs:
            - default
          # parse: json 
          labels:
            cluster: "aws"
      # outputs:
      #   - name: cw-output
      #     type: cloudwatch 
      #     cloudwatch:
      #       groupBy: logType 
      #       groupPrefix: ${CLOUDWATCH_GROUP_PREFIX}
      #       region: ${AWS_DEFAULT_REGION}
      #     secret:
      #         name: ${AWS_SECRET_NAME} 