---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance 
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed  
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  visualization:
    type: ocp-console  
    # nodeSelector:
    #   node-role.kubernetes.io/infra: ''
  collection:
    type: vector
    resources:
      # limits:
      #   memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
