---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # inputs:
    # - name: quarkus-observability-logs
    #   application:
    #     namespaces:
    #       - quarkus-observability
  # outputs:
    # - name: rsyslog-bastion
    #   type: syslog
    #   syslog:
    #     facility: local0
    #     rfc: RFC5424
    #     severity: informational
    #   url: 'tcp://X.X.X.X:514'   # Bastion
    # - name: cw-output
    #   type: cloudwatch 
    #   cloudwatch:
    #     groupBy: logType 
    #     groupPrefix: ${CLOUDWATCH_GROUP_PREFIX}
    #     region: ${AWS_DEFAULT_REGION}
    #   secret:
    #       name: ${AWS_SECRET_NAME} 
  pipelines:
    # - name: audit-logs-to-rsyslog
    #   inputRefs:
    #     - audit
    #   outputRefs:
    #     - rsyslog-bastion
    # - name: quarkus-observability
    #   inputRefs: 
    #     - quarkus-observability-logs
    #   outputRefs:
    #     - cw-output 
    #   parse: json 
    #   labels:
    #     test: "alvaro" 
    - name: default
      inputRefs:
        - application
        - infrastructure
        - audit
      outputRefs:
        - default
