---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clo-cluster-logging-write-infrastructure-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-write-infrastructure-logs
subjects:
- kind: ServiceAccount
  name: cluster-logging-operator
  namespace: openshift-logging
