---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - 01-clo-operator
  - 02-loki-operator

  # S3 Bucket alterative if using ODF
  # - obc-loki-bucket-odf.yaml
  # - 04-create-odf-s3-secret

  # Logs Storage
  - lokistack-logging-loki.yaml

  # Log RBAC
  - crb-clo-collect-application-logs.yaml
  - crb-clo-collect-audit-logs.yaml
  - crb-clo-collect-infrastructure-logs.yaml
  ## Allow write anything 
  - crb-clo-logging-collector-logs-writer.yaml
  ## Segregate write permission
  # - crb-clo-write-application-logs.yaml
  # - crb-clo-write-audit-logs.yaml
  # - crb-clo-write-infrastructure-logs.yaml

  # Log Forwarding
  - clusterlogforwarder-collector.yaml

  # # Logs Collection and Visualization
  # - clusterlogging-instance.yaml
