name: build-and-push-quay

run-name: Build and Push Container image to Quay.io 🚀

env:
  IMAGE_BASE_NAME: "quay.io/alopezme/quarkus-observability-app"
  # MANDREL_IMAGE: "quay.io/quarkus/ubi-quarkus-mandrel-builder-image"
  # MANDREL_VERSION: "22.3"
  # LATEST_IMAGE_TAG: "latest"
  # NATIVE_JAVA_VERSION: "17"

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'releases/**'
      - 'main'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - '*.yaml'
      # - 'README.md'

# This section ensures that new pushes cancel current executions of the workflow
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-native-artifact:
    runs-on: ubuntu-latest
    name: "Build Native Package"
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the code
        uses: actions/checkout@v3
      # https://github.com/orgs/community/discussions/55854
      # - name: Verify Semver
      - name: Build native executable
        uses: maxday/quarkus-native-build-docker-action@13bf5c4ae6942143cf43a5663a6c7f847ac3163c
        with:
          outputName: app-runner
      # https://github.com/softprops/action-gh-release
      - name: Release if is a new tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app-runner
          draft: true
      - name: Upload native executable
        uses: actions/upload-artifact@v3
        with:
          name: native-executable
          path: app-runner


#   build-native-image:
#     runs-on: ubuntu-latest
#     name: "Build Native Image"
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v3
#       - name: Download the binary
#         uses: actions/download-artifact@v1
#         with:
#           name: native-executable


# # https://github.com/ishworkh/docker-image-artifact-upload

#   push-image-to-quay:
#     runs-on: ubuntu-latest
#     name: "Push image to Quay"
#     needs:
#       - build-native-image
#     steps:
#       - name: Login to quay
#         uses: docker/login-action@v2
#         with:
#           registry: quay.io
#           username: ${{ secrets.QUAY_REPO_USERNAME }}
#           password: ${{ secrets.QUAY_REPO_TOKEN }}

#       - name: Build and push UI image
#         uses: docker/build-push-action@v4
#         with:
#           context: ui-super-heroes
#           platforms: linux/amd64,linux/arm64
#           push: true
#           tags: ${{ env.IMAGE_BASE_NAME }}/ui-super-heroes:${{ env.CONTAINER_TAG }},${{ env.IMAGE_BASE_NAME }}/ui-super-heroes:${{ env.APP_VERSION }}
