name: build-and-push-quay

run-name: Build and Push Container image to Quay.io 🚀

env:
  IMAGE_BASE_NAME: "quay.io/alopezme/quarkus-observability-app"
  IMAGE_TAG: "1.0.0"
  NATIVE_JAVA_VERSION: "17"

# This section allows the workflow to create a Release
permissions:
  contents: write

# This section ensures that new pushes cancel current executions of the workflow
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'releases/**'
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - 'LICENSE'
      - '*.yaml'
      # - 'README.md'

jobs:
  build-native-artifact:
    runs-on: ubuntu-latest
    name: "Build Native Package"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      # https://github.com/orgs/community/discussions/55854
      # - name: Verify Semver

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.NATIVE_JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: Build native executable
        run: ./mvnw install --no-transfer-progress -Dnative -DskipTests -Dquarkus.native.remote-container-build=true

      - name: Release if is a new tag
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*-runner
          body: This release is still part of the tests of the CI/CD pipeline!
          draft: true
      - name: Upload native executable
        uses: actions/upload-artifact@v3
        with:
          name: native-executable
          path: target/*-runner


  build-and-push-image:
    runs-on: ubuntu-latest
    needs: 
      - build-native-artifact
    name: "Build Native Image"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Download the native executable
        uses: actions/download-artifact@v3
        with:
          name: native-executable
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_REPO_USERNAME }}
          password: ${{ secrets.QUAY_REPO_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: src/main/docker/Dockerfile.native
          tags: ${{ env.IMAGE_BASE_NAME }}:${{  github.ref_name }}
# # https://github.com/ishworkh/docker-image-artifact-upload
